### PR TITLE
Familiar names are not showing up on the creation of a familiar FIXED

### LINKED ISSUE #75: Familiar names are not showing up on the creation of a familiar

### PR DESCRIPTION
**Pull request by OtisGoodman**
#75 Fixed

### CODE REVIEW

**Comment by OtisGoodman** [comment]
if your not satisfied I can try something else.

**Comment by zabi94** [comment]
Yeah, the problem can be definitely be solved in a more elegant, object oriented way. Checking for the class is a clear marker that the code can be better. 
Also, why not use instanceof instead, anyways?

**Comment by OtisGoodman** [comment]
I did not think of that

**Comment by zabi94** [comment]
The build is also failing btw, the code doesn't compile

**Comment by OtisGoodman** [comment]
RIP in that case I will try something else

**Pull request closed without merging**
