### PR TITLE
Added Gem Bowl

### PR DESCRIPTION
**Pull request by rustylocks79**
- Added a new Tile Entity Gem Bowl
- Right-clicking on the bowl with an accepted gem places it in the bowl. 
- Accepted gems can be added easily by modifying the ACCEPTED_ORE_NAMES constant at the top of TileEntityGemBowl
- Right-clicking on the bowl with an empty hand removes the current gem.
- Moved the Gain Amount for gems from TileEntityWitchAltar to TileEntityGemBowl

### CODE REVIEW

**Comment by Sunconure11** [comment]
Merge now or wait?

**Comment by zabi94** [comment]
Well, Travis is complaining about check style, we should just disable the option honestly. If you can test it a little bit to see if everything works as intended, do it, otherwise I'll merge when I get the chance to test it myself

**Comment by Sunconure11** [comment]
He just needs to use tabs instead of spaces, according to the log

**Comment by Sunconure11** [comment]
I'll merge it in a bit, and test it.

**Pull request merged**
