### PR TITLE
Cursed Amulet Added (Texture Required)

### PR DESCRIPTION
**Pull request by OtisGoodman**

### CODE REVIEW

**Comment by zabi94** [comment]
Also, where does this come from? I'm pretty sure I've never hear about this. Is this just an idea of yours or did you follow someone's todo?

**Comment by Sunconure11** [comment]
We're trying to have way less Harry Potter references than what Witchery had.

**Comment by OtisGoodman** [comment]
ok

**Comment by OtisGoodman** [comment]
Would you like to see this added? or would it better if we don't have it?
This is supposed to be used as a troll item so when you put it on you go flying up in the air.

**Comment by Sunconure11** [comment]
It would only be effective if players actually did not know what it did. Besides, let the devs handle new content for indev for now.

**Comment by OtisGoodman** [comment]
Ok deal

**Comment by OtisGoodman** [comment]
You can delete this if you want

**Pull request closed without merging**
