### PR TITLE
Fix/lantern raise correct hand

### PR DESCRIPTION
**Pull request by DaveArndt**
This is just a stopgap measure to make it look a little better.

### CODE REVIEW

**Comment by Sunconure11** [comment]
Safe to merge yet?

**Comment by DaveArndt** [comment]
Yeah, just not working perfectly. I put more info in the issue

**Comment by Sunconure11** [comment]
@zabi94 @Ingoleth

**Comment by Ingoleth** [comment]
Not much I can do, I just did the model...

**Pull request merged**
